spring:
  datasource:
    url: jdbc:mysql://localhost:3307/movie
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bailey
    password: bailey
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
